<div id="top_detail">
<div id="top_detail_inner">
						<div id="per_yc">
							<div class="per_img"><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="130" />
								<h2>TableClock CITY HALL </h2>
								<em>定価：13,230円（税込）</em>
								<li><a href="<?php echo $site_url;?>/centerprophet/goods?prophet_id=2">修改</a>&nbsp;<a href="">删除</a></li>
							</div>
							<div class="per_img"><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="130" />
								<h2>TableClock CITY HALL </h2>
								<em>定価：13,230円（税込）</em>
								<li><a href="<?php echo $site_url;?>/centerprophet/goods?prophet_id=2">修改</a>&nbsp;<a href="">删除</a></li>
							</div>
							<div class="per_img"><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="130" />
								<h2>TableClock CITY HALL </h2>
								<em>定価：13,230円（税込）</em>
								<li><a href="<?php echo $site_url;?>/centerprophet/goods?prophet_id=2">修改</a>&nbsp;<a href="">删除</a></li>
							</div>
							<div class="per_img"><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="130" />
								<h2>TableClock CITY HALL </h2>
								<em>定価：13,230円（税込）</em>
								<li><a href="<?php echo $site_url;?>/centerprophet/goods?prophet_id=2">修改</a>&nbsp;<a href="">删除</a></li>
							</div>
							<div class="per_img"><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="130" />
								<h2>TableClock CITY HALL </h2>
								<em>定価：13,230円（税込）</em>
								<li><a href="<?php echo $site_url;?>/centerprophet/goods?prophet_id=2">修改</a>&nbsp;<a href="">删除</a></li>
							</div>
						</div>
</div>
</div>