<div id="top_detail">
					<div id="top_detail_inner">
						
						<h3>商品信息修改：</h3>
						<div id="upload_ser">
							<form action="">
								<table class="upload_ser">
								<tr>
								<th>商品名</th>
								<td><input type="text" name="qq_number" value="" size="40"></td>
								</tr>
								
								<tr>
								<th>当前图片</th>
								<td><div><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="140" /></div></td>
								</tr>
								
								<tr>
								<th>上传新图片</th>
								<td><input type="file" name="..." size="40" input enctype="multipart/form-data" maxlength="100"></td>
								</tr>
								
								<tr>
								<th>详细描述</th>
								<td><textarea type="text" name="method_number" value="" style="width:225px;height:80px;"></textarea></td>
								</tr>
								
								<tr>
								<th>单价</th>
								<td><input type="text" name="qq_number" value="" size="40"></td>
								</tr>
								</table>
								
								<input class="ser_sub" name="button" type="submit" value="提交"/>
								
							</form>
							
						</div>
						
					</div>
</div>