<div id="l_clm">
				<h5><a href="<?php echo $site_url;?>prophet/index">预测师信息</a></h5>
	    <ul>
	   	      	   <li><a href="<?php echo $site_url;?>prophet/index">详细资料</a></li>
	      	   	   <li><a href="<?php echo $site_url;?>prophet/modify">资料修改</a></li>
	      	   	   <li><a href="">修改支付宝账号</a></li>
	    </ul>
				<h5><a href="<?php echo $site_url;?>prophet/sdetail">我的预测项</a></h5>
	    <ul>		<li><a href="<?php echo $site_url;?>prophet/sdetail">详细资料</a></li>
	   	      	   	<li><a href="<?php echo $site_url;?>prophet/supload">追加新预测项</a></li>
	    </ul>
				<h5><a href="<?php echo $site_url;?>prophet/article">我的随笔</a></h5>
	    <ul>
	   	      	   	<li><a href="<?php echo $site_url;?>prophet/article">我的随笔</a></li>
	    </ul>
				<h5><a href="<?php echo $site_url;?>money/pdetail/1">财务明细</a></h5>
	    <ul>
	   	      	   	<li><a href="<?php echo $site_url;?>money/pdetail/1">财务明细</a></li>
	      	   	    <li><a href="<?php echo $site_url;?>money/precord/1">交易记录</a></li>
	    </ul>
				<h5><a href="">客户消息</a></h5>
	    <ul>
	   	      	     <li><a href="<?php echo $site_url;?>message/pinformation">新消息</a></li>
	      	   	     <li><a href="<?php echo $site_url;?>message/precord">交谈记录</a></li>
	      	   	     <li><a href="<?php echo $site_url;?>order/ptest">测试记录</a></li>
	    </ul>
			   <h5><a href="">待定</a></h5>
	    <ul>
	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	      	   	   	</ul>
	</div>