<div id="top_detail">
					<div id="top_detail_inner">
						
						<h3>测试记录：</h3>
						<div id="property_mes">
							<table class="property_mes">
							<tr>
							<th><strong>客户名</strong></th>
							<th><strong>测试内容</strong></th>
							<th><strong>开始时间</strong></th>
							<th><strong>结束时间</strong></th>
							<th><strong>操作</strong></th>
							</tr>
							
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td><a href="">查看</a> &nbsp; <a href="">删除</a></td>
						
							</tr>
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td><a href="">查看</a> &nbsp; <a href="">删除</a></td>
							
							</tr>
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td><a href="">查看</a> &nbsp; <a href="">删除</a></td>
							
							</tr>
							</table>
						</div>
						
					</div>
</div>