<div id="top_detail">

					<div id="top_detail_inner">
						<p class="p_per">完善个人信息:</p>
					<form action="" class="form_per">
						<table class="table_per">
							<tbody>
								<tr>
									<th>电子邮箱</th>
									
									<td><label id="email" class="hide" style="display:block">11111</label></td>
								</tr>
								<tr>
									<th>用户名</th>
									
									<td><label id="name" class="hide" style="display:block">11111</label></td>
								</tr>
								<tr>
									<th>邮编号码</th>
									
											<td>
												<a name="zipcode_pdata"></a>
												<input type="text" name="zipcode1" value="" size="5" maxlength="3"> -
												<input type="text" name="zipcode2" value="" size="7" maxlength="4">
												<input type="button" value="検索" class="searchAddress1">
											</td>
								</tr>
								<tr>
											<th>地址1</th>
											
											<td><em>国</em>
												<select name="local_cd" id='select_id'>
													<option value="">请选择</option>
												</select>
												<em>省</em>
												<select name="local_cd" id='select_id'>
													<option value="">请选择</option>
													<option label="北海道" value="01">北海道</option>
												</select>
												<em></em>
											</td>
								</tr>
								<tr>
											<th>地址2</th>
											
											<td>
												<em>市</em>
												<select name="local_cd" id='select_id'>
													<option value="">请选择</option>
													<option label="北海道" value="01">北海道</option>
												</select>
												<em>区</em>
												<select name="local_cd" id='select_id'>
													<option value="">请选择</option>
													<option label="北海道" value="01">北海道</option>
												</select>
												<em></em>
											</td>
								</tr>
								<tr>
											<th>详细地址</th>
											
											<td>
												<input type="text" name="address" value="" size="40">
												<div class="notes">例）1-3-5 寿ビル6F</div>
												<em></em>
											</td>
								</tr>
								<tr>
											<th>电话号码</th>
											
											<td>
												<input type="text" name="tel_number1" value="" size="6"> -
												<input type="text" name="tel_number2" value="" size="6"> -
												<input type="text" name="tel_number3" value="" size="6">
											    <em>  </em>
											</td>
										</tr>
										<tr>
											<th>手机号码</th>
											
											<td>
												<input type="text" name="mobile_number1" value="" size="6"> -
												<input type="text" name="mobile_number2" value="" size="6"> -
												<input type="text" name="mobile_number3" value="" size="6">
												<em></em>
											</td>
										</tr>
										<tr>
											<th>
												QQ号码
											</th>
											
											<td><input type="text" name="qq_number" value="" size="40"></td>
										</tr>
										<tr>
											<th>出生年月</th>
											
											<td>
												<select name="birth1">
													<option value="">请选择</option>
												<option label="2000" value="2000">2000</option>
<option label="1999" value="1999">1999</option>
<option label="1998" value="1998">1998</option>

<option label="1925" value="1925">1925</option>
<option label="1924" value="1924">1924</option>

												</select> 年
												<select name="birth2">
													<option value="">请选择</option>
												<option label="01" value="01">01</option>
<option label="02" value="02">02</option>
<option label="03" value="03">03</option>
<option label="04" value="04">04</option>
<option label="05" value="05">05</option>
<option label="06" value="06">06</option>
<option label="07" value="07">07</option>
<option label="08" value="08">08</option>
<option label="09" value="09">09</option>
<option label="10" value="10">10</option>
<option label="11" value="11">11</option>
<option label="12" value="12">12</option>

												</select> 月
												<em>  </em>
											</td>
										</tr>
										<tr>
											<th>性別</th>
											
											<td>
												<label><input type="radio" name="sex" value="1" />女性</label>
<label><input type="radio" name="sex" value="2" />男性</label>
												<em></em>
											</td>
										</tr>
							</tbody>
						</table>
								<a class="a_per" href="#" onClick="" title="戻る">戻る</a>
								<input class="sub_per" type="submit" title="内容を確認する">
					</form>
					</div>
					
				</div>