<div id="top_detail">
					<div id="top_detail_inner">
						<h3 class="p_per">总览：</h3>
						<div id="main_property">
							<div class="per_img"><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="130" /></div>
							<div id="property_mess">
								<table class="property_mes">
								<tr>
								<th>预测师名</th>
								<td>aaaaaaaaaaa</td>
								</tr>
								
								
								<tr>
								<th>账户余额</th>
								<td>aaaaaaaaaaa</td>
								</tr>
								
								<tr>
								<th>最近一次进账时间</th>
								<td>aaaaaaaaaaa</td>
								<th>金额</th>
								<td>aaaaaaaaaaa</td>
								
								</tr>
								
								<tr>
								<th>最近一次提现时间</th>
								<td>aaaaaaaaaaa</td>
								<th>金额</th>
								<td>aaaaaaaaaaa</td>
								
								</tr>
								</table>
							</div>
						</div>
						
						<h3>收入记录：</h3>
						<div id="property_mes">
							<table class="property_mes">
							<tr>
							<th><strong>预测师名</strong></th>
							<th><strong>收入金额</strong></th>
							<th><strong>收入项目</strong></th>
							<th><strong>操作时间</strong></th>
							</tr>
							
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td><a href ="">aaaaaaaaaaa</a></td>
							<td>aaaaaaaaaaa</td>
						
							</tr>
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td><a href ="">aaaaaaaaaaa</a></td>
							<td>aaaaaaaaaaa</td>
							
							</tr>
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td><a href ="">aaaaaaaaaaa</a></td>
							<td>aaaaaaaaaaa</td>
							
							</tr>
							</table>
						</div>
						
						<h3>提现记录：</h3>
						<div id="property_mes">
							<table class="property_mes">
							<tr>
							<th><strong>预测师名</strong></th>
							<th><strong>提现金额</strong></th>
							<th><strong>操作时间</strong></th>
							</tr>
							
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
						
							</tr>
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							
							</tr>
							
							<tr>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							<td>aaaaaaaaaaa</td>
							
							</tr>
							</table>
						</div>
						
					</div>
</div>