<div id="top_detail">
					<div id="top_detail_inner">
						<h3 class="p_per">预测师资料:</h3>
						<div id="porphet_menu">
							<div class="prophet_img"><img src="<?php echo $site_url; ?>/imgr/shop_img/test01_0.jpg" height="130" /></div>
							<div class="prophet_mes">
								<table class="prophet_mess">
								<tr>
								<th class="prophet_td1">用户名：</th><td>1111</td>
								<th class="prophet_td1">预测师名：</th><td>1111</td>
								</tr>
								
								<tr>
								<th class="prophet_td1">邮箱：</th><td>1111</td>
								<th class="prophet_td1">账户号：</th><td>1111</td>
								</tr>
								
								<tr>
								<th class="prophet_td1">真实姓名：</th><td>1111</td>
								<th class="prophet_td1">性别：</th>
								<td>1111</td>
								</tr>
								
								<tr>
								<th class="prophet_td1">手机：</th>
								<td>1111</td>
								<th class="prophet_td1">qq：</th>
								<td>1111</td>
								</tr>
								
								<tr>
								<th class="prophet_td1">联系地址：</th>
								<td>1111</td>
								<th class="prophet_td1">申请预测师时间：</th>
								<td>1111</td>
								</tr>
								</table>
								<!-- 
								<li><span>用户名:</span><label id="">11111</label></li>
								<li><span>预测师名:</span><label id="">11111</label></li>
								<li><span>邮箱:</span><label id="">11111</label></li>
								<li><span>账户号:</span><label id="">11111</label></li>
								<li><span>真实姓名:</span><label id="">11111</label></li>
								<li><span>性别:</span><label id="">11111</label></li>
								<li><span>出生年月:</span><label id="">11111</label></li>
								<li><span>手机:</span><label id="">11111</label></li>
								<li><span>电话:</span><label id="">11111</label></li>
								<li><span>联系地址:</span><label id="">11111</label></li>
								<li><span>申请预测师时间:</span><label id="">11111</label></li>
								 -->
							</div>
						</div>
						<h3>预测师简介：</h3>
						<div id="prophet_cont">
							<br/>
							<h1 class="h1_cont">我的简介</h1><br>
							<h2 class="h2_cont">不知己命非君子，糊里糊涂过一生</h2>
							<h2 class="h2_cont">一点一滴总关易-----致全世界相信和需要依靠中华5000年预测文化指导人生的朋友们
							</h2>
							<h2 class="h2_cont">---------丁火-导航人生</h2>
							<p>台湾大学教授、现代易学家曾仕强座客央视--易经的奥秘讲：人是有命的。从生下来的那一刻，就决定了我们每个人的高贵贫贱。</p>
							<p>
							我家祖上是专门为朝廷做风水、命理堪舆术数预测的命师，一致到清朝末，八府巡官每年都要代表朝廷到我们家拜访，以示对国师的尊重。
							后人多有职业风水、命理师出一家。到我出生的时候，家祖爷是本地有名的风水命理师。我大学毕业以后在学校任教，得天独厚的条件，加上从小受祖师爷耳染目濡熏陶，对命理学有了独特的爱好。
							在大学坚持学习《易经》、《易传》、《易经.系辞》等古书。开始接受中国传统文化，并结合预测学深入研究如何运用传统文化指导人生，如何趋吉避凶，如何加强道德修养，如何自强不息。
							后来因为一场病，开始研究算命术。第一次下海大潮期间，本人放弃大学职业，专业从事风水、预测业。
							出世自带慈善救世密码，天人感应，无师自通。目前主要从事风水、命理预测、带徒，受测客户遍及香港、台湾、澳大利亚等东南亚国家和全世界各个地区的华人华侨，擅长玄空风水、盲派八字、六爻、面相等预测。</p>
							<p>
							目前已经为数以万计的客户预测指导服务，积德于民。成为一代皇室八字六爻算命帝王风水面相改运授徒宗师，把盲派预测文化推进了一个新的高度。同时还研究发表了200多篇预测理论文章，受到社会广泛好评。
							以文识人，以文会友，由于本人得家书和祖师秘传，很多理论用于实践有惊人的准确性，各派高手纷纷汇聚门下，相得益彰，现坐镇算卦街，为全球华人做风水、命理、事业、婚姻和财运、看相、起名、开运服务为大家趋吉避凶助运送福。</p>
							<br/>
							现为算卦街<a href="/">真人在线算命一条街</a>特聘算命大师。
						</div>
		
					</div>
</div>